import re
import json
import os
from dataclasses import dataclass

from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = None

MODEL = "llama-3.3-70b-versatile"

PROMPT_TEMPLATE = """You are an expert at detecting whether text was written by a human or an AI language model.

Analyze the following text and estimate the probability it was generated by an AI.

Look for:
- Sentence structure uniformity (AI text is very consistent; human text varies)
- Vocabulary choices (AI often hedges, uses transitional phrases like "Furthermore", "It is worth noting")
- Specificity of detail (humans cite concrete, particular details; AI generalizes)
- Stylistic idiosyncrasies — typos, unconventional choices, personal voice (human markers)
- Emotional authenticity and texture (genuine human emotion has rough edges; AI emotion is smooth)
- Perfectly balanced structure or an uncanny sense of completeness (AI signal)

Text to analyze:
<text>
{text}
</text>

Respond with ONLY a valid JSON object — no markdown fences, no commentary outside the JSON:
{{
  "ai_probability": <float from 0.0 to 1.0>,
  "reasoning": "<one concise sentence naming the strongest signal you observed>"
}}

Where ai_probability is P(text was AI-generated): 1.0 = certainly AI, 0.0 = certainly human."""


@dataclass
class LLMResult:
    score: float       # P(AI): 0.0 = human, 1.0 = AI
    reasoning: str
    model: str


def classify(text: str) -> LLMResult:
    """
    Sends text to a Groq-hosted LLM for semantic AI/human classification.
    Returns P(AI) score and one-sentence reasoning.
    Falls back to 0.5 (uncertain) if the API call fails.
    """
    client = _get_client()
    if client is None:
        return LLMResult(score=0.5, reasoning="GROQ_API_KEY not configured", model=MODEL)

    prompt = PROMPT_TEMPLATE.format(text=text[:4000])

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=256,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if the model wraps its output
        raw = re.sub(r"```[a-z]*\n?", "", raw).strip("`\n ")

        data = json.loads(raw)
        ai_prob = float(data.get("ai_probability", 0.5))
        ai_prob = max(0.0, min(1.0, ai_prob))
        reasoning = str(data.get("reasoning", "No reasoning provided."))

        return LLMResult(score=round(ai_prob, 4), reasoning=reasoning, model=MODEL)

    except json.JSONDecodeError as exc:
        return LLMResult(
            score=0.5,
            reasoning=f"JSON parse error from model response: {str(exc)[:80]}",
            model=MODEL,
        )
    except Exception as exc:
        return LLMResult(
            score=0.5,
            reasoning=f"Classification unavailable: {str(exc)[:80]}",
            model=MODEL,
        )


def _get_client():
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            return None
        _client = Groq(api_key=api_key)
    return _client
